

name: Windows exe

on:
  push:
    branches: [ "main" ]
  # workflow_call:
  #   inputs:
  #     binary-artifact-name:
  #       required: true
  #       type: string


jobs:
  build:
    runs-on: 
        - Windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    if: ${{ github.actor == 'HarishKumarSedu' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: python setup 
        uses: actions/setup-python@v5 
      - name: build exe package
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -U
          python -m pyinstaller --onfile main.py 
          ls -a 
      - name : Build Zip file 
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'ivm-gui.zip'
          path: ${{github.workspace}}/dist

      - name: post zip
        run: |
          dir
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ivm-gui
          path: ${{github.workspace}}/ivm-gui.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ivm-gui
          path: ${{ github.workspace }}/ivm-gui.zip
      - name: List Checkout files 
        run: |
          dir 
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude="" --include="" --filter=""
          path: report.txt
          remote_path: ${{ secrets.DEPLOY_PATH }} 
          remote_host: ${{ secrets.DEPLOY_HOST }} 
          remote_port: ${{ secrets.DEPLOY_PORT }} 
          remote_user: ${{ secrets.DEPLOY_USER }} 
          remote_key: ${{ secrets.DEPLOY_KEY }}  
      # - name: Git Config
      #   run: |

      #     git config user.name github-actions[bot]
      #     git config user.email github-actions[bot]@users.noreply.github.com
      #     git add ivm-gui
      #     git commit -am "test files added" 
      #     echo "${{ github.ref }}"
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
    
