

name: Windows exe

on:
  push:
    branches: [ "main" ]
  # workflow_call:
  #   inputs:
  #     binary-artifact-name:
  #       required: true
  #       type: string


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v3
  #       with:
  #          python-version: ${{ matrix.python-version }}
  #     - name: build exe package
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt -U
  #         python exe.py build
  #         dir 

  #     - name : Build Zip file 
  #       uses: thedoctor0/zip-release@0.7.5
  #       with:
  #         type: 'zip'
  #         filename: 'ivm-gui.zip'
  #         path: ${{github.workspace}}/build

  #     - name: post zip
  #       run: |
  #         dir
  #     - name: Upload binary artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ivm-gui
  #         path: ${{github.workspace}}/ivm-gui.zip
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: ivm-gui
  #         path: ${{ github.workspace }}/ivm-gui.zip
  #     - name: List Checkout files 
  #       run: |
  #         ls -a 
      # - name: rsync deployments
      #   uses: burnett01/rsync-deployments@5.2
      #   with:
      #     switches: -avzr --delete --exclude="" --include="" --filter=""
      #     path: ivm-gui.zip
      #     remote_path: ${{ secrets.DEPLOY_PATH }} 
      #     remote_host: ${{ secrets.DEPLOY_HOST }} 
      #     remote_port: ${{ secrets.DEPLOY_PORT }} 
      #     remote_user: ${{ secrets.DEPLOY_USER }} 
      #     remote_key: ${{ secrets.DEPLOY_KEY }}  
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'HarishKumarSedu'
          git config --global user.email 'harishkumarsedu@gmail.com'
          git remote set-url origin https://HarishKumarSedu:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git add *
          git commit -am "Automated report"
          git push origin main
    