

name: Windows exe

on:
  push:
    branches: [main]
  # workflow_call:
  #   inputs:
  #     binary-artifact-name:
  #       required: true
  #       type: string


jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
           python-version: ${{ matrix.python-version }}
      - name: build package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -U
          python exe.py build
          dir 
      # - name: Install zip
      #   uses: montudor/action-zip@v1

      # - name: Zip output
      #   run: zip -qq -r gui.zip build
      #   working-directory: ${{github.workspace}}
      # - name: Build Zipfile
      #   run: |
      #     dir
          
      #     Compress-Archive -Path build/ -DestinationPath /gui.zip
      #     dir
      # - name: post zip
      #   run: dir

      # - name: rsync deployments
      #   uses: burnett01/rsync-deployments@5.2
      #   with:
      #     switches: -avzr --delete --exclude="" --include="" --filter=""
      #     path: gui.zip
      #     remote_path: ${{ secrets.DEPLOY_PATH }} 
      #     remote_host: ${{ secrets.DEPLOY_HOST }} 
      #     remote_port: ${{ secrets.DEPLOY_PORT }} 
      #     remote_user: ${{ secrets.DEPLOY_USER }} 
      #     remote_key: ${{ secrets.DEPLOY_KEY }}  
      - name : Build Zip file 
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'gui.zip'
          path: ${{github.workspace}}/build
