

name: Windows exe

on:
  push:
    branches: [main]
  # workflow_call:
  #   inputs:
  #     binary-artifact-name:
  #       required: true
  #       type: string


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
           python-version: ${{ matrix.python-version }}
      - name: build package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -U
          python exe.py build
          ls -a 
      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: zip -qq -r gui.zip build
        working-directory: ${{github.workspace}}
      
      - name: post zip
        run: ls -a 

      # - name: Build Zipfile
      #   run: |
      #     dir
      #     cd D:\a\ivm-test-gui\ivm-test-gui\dist\pyinstaller\win_amd64\
      #     Compress-Archive -Path .\ivm-gui\ -DestinationPath .\ivm-gui.zip
      #     dir
      # - name: Upload binary artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ inputs.binary-artifact-name }}
      #     path: D:\a\ivm-test-gui\ivm-test-gui\dist\pyinstaller\win_amd64\ivm-gui.zip
